Add support for Easun SV serie
jblance/mpp-solar pull request #276
Opened 2022-12-12 16:44 UTC by sand1812

Added support for Easun SV inverters.
Has been tested on SV-IV 5.6 with parallel boards.

All read requests works.
Some set requests return NACK
Some set requests not yet implemented (waiting to find out why some don't work)

2022-12-12 20:26 UTC, jblance commented on mppsolar/protocols/pi18sv.py
> +        self.STATUS_COMMANDS = ["PI","T","ET","EY","EM","ED","ID","VFW","PIRI","GS","MOD","FWS","FLAG","DI","CHGCR","MUCHGCR","PRI","PGS","ACCT","ACLT"]
STATUS_COMMANDS are the commands to run when a --getStatus command is issued. This list looks too long (normally it is 1 or 2 or 3 key commands)

2022-12-12 20:35 UTC, jblance requested changes
I've made a few comments, do they make sense?
Mostly the requested changes are to make the code easy to keep up to date for multiple different systems.

Thoughts?

2022-12-12 20:35 UTC, jblance commented on mppsolar/protocols/pi18sv.py
> +        self.SETTINGS_COMMANDS = [
as above, this is the --getSettings command, so the list is likely too long

2022-12-13 14:40 UTC, sand1812 commented
Hi,

Your comments looks right. I've lot of work today & tomorrow. I’ll update my code later this week. But feel free to do it if you want !

Do you have any idea why the SET commands are mostly not working ? 
For example, according to doc, « BUCD500,540 » should be ok, but the inverter returns 0 (failed)

I attached the doc from easun for reference.

Kind regards,

Greg.



> Le 12 déc. 2022 à 21:35, John Blance ***@***.***> a écrit :
> 
> 
> @jblance requested changes on this pull request.
> 
> I've made a few comments, do they make sense?
> Mostly the requested changes are to make the code easy to keep up to date for multiple different systems.
> 
> Thoughts?
> 
> In mppsolar/protocols/pi18sv.py:
> 
> > +        "regex": "BUCD(\\d\\d\\d,\\d\\d\\d)$",
> +    },
> +    
> +}
> +
> +
> +class pi18sv(AbstractProtocol):
> +    def __str__(self):
> +        return "PI18-SV protocol handler"
> +
> +    def __init__(self, *args, **kwargs) -> None:
> +        super().__init__()
> +        self._protocol_id = b"PI18SV"
> +        self.COMMANDS = COMMANDS
> +        self.STATUS_COMMANDS = ["PI","T","ET","EY","EM","ED","ID","VFW","PIRI","GS","MOD","FWS","FLAG","DI","CHGCR","MUCHGCR","PRI","PGS","ACCT","ACLT"]
> +        self.SETTINGS_COMMANDS = [
> 
> as above, this is the --getSettings command, so the list is likely too long
> 
> In mppsolar/protocols/pi18sv.py:
> 
> > +        ],
> +        "regex": "BUCD(\\d\\d\\d,\\d\\d\\d)$",
> +    },
> +    
> +}
> +
> +
> +class pi18sv(AbstractProtocol):
> +    def __str__(self):
> +        return "PI18-SV protocol handler"
> +
> +    def __init__(self, *args, **kwargs) -> None:
> +        super().__init__()
> +        self._protocol_id = b"PI18SV"
> +        self.COMMANDS = COMMANDS
> +        self.STATUS_COMMANDS = ["PI","T","ET","EY","EM","ED","ID","VFW","PIRI","GS","MOD","FWS","FLAG","DI","CHGCR","MUCHGCR","PRI","PGS","ACCT","ACLT"]
> 
> STATUS_COMMANDS are the commands to run when a --getStatus command is issued. This list looks too long (normally it is 1 or 2 or 3 key commands)
> 
> In mppsolar/protocols/pi18sv.py:
> 
> > +        "help": " -- BUCDmmm,nnn with mmm battery recharge voltage when utility available (44 to 51V) and nnn Battery re-discharged voltage when utility is available (0,48-58)",
> +        "type": "SETTER",
> +        "response": [
> +            ["ack", "Command execution", {"NAK": "Failed", "ACK": "Successful"}],
> +        ],
> +        "test_responses": [
> +            b"^1\x0b\xc2\r",
> +            b"^0\x1b\xe3\r",
> +        ],
> +        "regex": "BUCD(\\d\\d\\d,\\d\\d\\d)$",
> +    },
> +    
> +}
> +
> +
> +class pi18sv(AbstractProtocol):
> 
> would prefer to inherit from pi18 and only have the differences in this one, see latest pi30max for example (if youre not comfortable doing this I can do it later)
> 
> In mppsolar/protocols/pi18sv.py:
> 
> > +                full_command = _pre_cmd + bytes([13])
> +            else :
> +                full_command = _pre_cmd + bytes([13])  + _crc            
> +            log.debug(f"full command: {full_command}")
> +            return full_command
> +        elif _type == "SETTER":
> +            data_length1 = len(_cmd) + 4
> +            _prefix = '^'+self._command_defn["prefix"]
> +            log.debug(f"_prefix: {_prefix}")
> +            #intermedstr = _prefix + "T" #+ self._command
> +            intermedstr = _prefix + self._command
> +            _pre_cmd = bytes(intermedstr, "utf-8")
> +            log.debug(f"_pre_cmd: {_pre_cmd}")
> +            crc_high, crc_low = crc(_pre_cmd)
> +            _crc = bytes([crc_high, crc_low, 13])
> +            if self._command_defn["crc"] == False:
> 
> I'd invert this, ie have a "nocrc" field, and no require the field
> so no "nocrc" field means 'have a crc' and "nocrc: False" means no crc, this way the commands in pi18 are usable and default to using a crc
> 
> In mppsolar/protocols/pi18sv.py:
> 
> > @@ -0,0 +1,1008 @@
> +import logging
> +
> +from .abstractprotocol import AbstractProtocol
> +
> +from .protocol_helpers import crcPI as crc
> +
> +# from .pi30 import COMMANDS
> +
> +log = logging.getLogger("18sv")
> +
> +COMMANDS = {
> 
> if we inherit from pi18, any commands that are the same do not need to re-defined, any that are the same but have improvements here should have those improvements in pi18
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.
>

2022-12-16 04:06 UTC, jblance commented
sorry i didnt see the doc
re commands not working, first check with debug to make sure the correct command is being sent - commas in particular are a bit half removed
the other thing ive seen is different padding for values, sometimes extra leading seros are needed

2022-12-16 04:06 UTC, merged